# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/lab/qconf_learn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/lab/qconf_learn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/lab/qconf_learn/CMakeFiles /workspace/lab/qconf_learn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/lab/qconf_learn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qconf_shm

# Build rule for target.
qconf_shm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qconf_shm
.PHONY : qconf_shm

# fast build rule for target.
qconf_shm/fast:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/build
.PHONY : qconf_shm/fast

log.o: log.cc.o
.PHONY : log.o

# target to build an object file
log.cc.o:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/log.cc.o
.PHONY : log.cc.o

log.i: log.cc.i
.PHONY : log.i

# target to preprocess a source file
log.cc.i:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/log.cc.i
.PHONY : log.cc.i

log.s: log.cc.s
.PHONY : log.s

# target to generate assembly for a file
log.cc.s:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/log.cc.s
.PHONY : log.cc.s

qlibc/md5.o: qlibc/md5.c.o
.PHONY : qlibc/md5.o

# target to build an object file
qlibc/md5.c.o:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/md5.c.o
.PHONY : qlibc/md5.c.o

qlibc/md5.i: qlibc/md5.c.i
.PHONY : qlibc/md5.i

# target to preprocess a source file
qlibc/md5.c.i:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/md5.c.i
.PHONY : qlibc/md5.c.i

qlibc/md5.s: qlibc/md5.c.s
.PHONY : qlibc/md5.s

# target to generate assembly for a file
qlibc/md5.c.s:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/md5.c.s
.PHONY : qlibc/md5.c.s

qlibc/qhash.o: qlibc/qhash.c.o
.PHONY : qlibc/qhash.o

# target to build an object file
qlibc/qhash.c.o:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/qhash.c.o
.PHONY : qlibc/qhash.c.o

qlibc/qhash.i: qlibc/qhash.c.i
.PHONY : qlibc/qhash.i

# target to preprocess a source file
qlibc/qhash.c.i:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/qhash.c.i
.PHONY : qlibc/qhash.c.i

qlibc/qhash.s: qlibc/qhash.c.s
.PHONY : qlibc/qhash.s

# target to generate assembly for a file
qlibc/qhash.c.s:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/qhash.c.s
.PHONY : qlibc/qhash.c.s

qlibc/qhasharr.o: qlibc/qhasharr.c.o
.PHONY : qlibc/qhasharr.o

# target to build an object file
qlibc/qhasharr.c.o:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/qhasharr.c.o
.PHONY : qlibc/qhasharr.c.o

qlibc/qhasharr.i: qlibc/qhasharr.c.i
.PHONY : qlibc/qhasharr.i

# target to preprocess a source file
qlibc/qhasharr.c.i:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/qhasharr.c.i
.PHONY : qlibc/qhasharr.c.i

qlibc/qhasharr.s: qlibc/qhasharr.c.s
.PHONY : qlibc/qhasharr.s

# target to generate assembly for a file
qlibc/qhasharr.c.s:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/qlibc/qhasharr.c.s
.PHONY : qlibc/qhasharr.c.s

shm.o: shm.cc.o
.PHONY : shm.o

# target to build an object file
shm.cc.o:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/shm.cc.o
.PHONY : shm.cc.o

shm.i: shm.cc.i
.PHONY : shm.i

# target to preprocess a source file
shm.cc.i:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/shm.cc.i
.PHONY : shm.cc.i

shm.s: shm.cc.s
.PHONY : shm.s

# target to generate assembly for a file
shm.cc.s:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/shm.cc.s
.PHONY : shm.cc.s

test.o: test.cc.o
.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i
.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s
.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) -f CMakeFiles/qconf_shm.dir/build.make CMakeFiles/qconf_shm.dir/test.cc.s
.PHONY : test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... qconf_shm"
	@echo "... rebuild_cache"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... qlibc/md5.o"
	@echo "... qlibc/md5.i"
	@echo "... qlibc/md5.s"
	@echo "... qlibc/qhash.o"
	@echo "... qlibc/qhash.i"
	@echo "... qlibc/qhash.s"
	@echo "... qlibc/qhasharr.o"
	@echo "... qlibc/qhasharr.i"
	@echo "... qlibc/qhasharr.s"
	@echo "... shm.o"
	@echo "... shm.i"
	@echo "... shm.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

